---
title: Plain Text Version of the *Titanic*
author: Your Name

format: 
  html:
    embed-resources: true
---


RMS Titanic was a British ocean liner that sank on 15 April 1912 after striking an iceberg on the ship's maiden voyage from Southampton, England to New York City, United States. Of the estimated 2,224 passengers and crew aboard, approximately 1,500 died, making the incident the deadliest sinking of a single ship at the time. Titanic, operated by the White Star Line (https://en.wikipedia.org/wiki/White_Star_Line), carried some of the wealthiest people in the world, as well as hundreds of emigrants from the British Isles, Scandinavia, and elsewhere in Europe who were seeking a new life in the United States and Canada. The disaster drew public attention, spurred major changes in maritime safety regulations, and inspired a lasting legacy in popular culture. Source: Wikipedia: https://en.wikipedia.org/wiki/Titanic.


Image path: imgs/1469px-RMS_Titanic_3.jpg


Why is the Titanic famous?

The Titanic is famous for many reasons, these include

She was the largest ship in the world.

She sank on her maiden voyage.

Her captain received many warnings of ice on the route but did not reduce speed.

There were not enough lifeboats for all the people on board.

Many crew and paying passengers lost their lives but the man that effectively owned the Titanic somehow survived.

With millionaires as well as people in dire poverty there was a diverse mix of passengers and crew and we have been left many fascinating stories of their lives.

Source: Encyclopedia Titanica: https://www.encyclopedia-titanica.org/titanic/


Dimensions of the Titanic

Length: 269.1 m
Beam:   28.2 m
Height: 53.3 m
Draught: 10.5 m
Depth: 19.7 m


Image path: imgs/compare_titanic_with_plane.jpg


Survival Rate

According to Encyclopedia Titanica (https://www.encyclopedia-titanica.org/), the survival rate of the passengers was as follows:

1-st class: 201/324 = 62.04%
2-nd class: 118/284 = 41.55%
3-rd class: 181/709 = 25.53%
Crew: 212/891 = 23.79%

Was Survival Dependent on Class?

I can never understand why God would have spared a poor Finnish girl when all those rich people drowned.

Anna Sofia Turja(https://www.encyclopedia-titanica.org/titanic-survivor/anna-sofia-turja.html (3rd-class passenger)

This quote raises the question: Were 1^st^-lass passengers more likely to survive than 3^rd^-class passengers? The data suggests that they were. The survival rate of 1^st^-class passengers was 62.04%, while the survival rate of 3^rd^-class passengers was only 25.53%. Crew members were even less likely to survive than 3^rd^-class passengers. The reason for this is that the crew members were responsible for ensuring the safety of the passengers and were therefore less likely to be able to save themselves in the event of an emergency. For passengers, the more luxurious the class, the more likely they were to survive, and the reason for this is that the 1^st^-class cabins were located closer to the lifeboats, making it easier for 1^st^-class passengers to reach them in time.


Image path: imgs/anna-turja_P1.jpg


Photo taken before the Titanic. Image from Encyclopedia Titanica: https://www.encyclopedia-titanica.org/titanic-survivor/anna-sofia-turja.html)


Data source: Encyclopedia Titanica: https://www.encyclopedia-titanica.org/.


The Titanic Movie (1997)

Image path: imgs/titanic_1997.png

The Titanic movie was released in 1997 and was directed by James Cameron. The movie was a huge success and won 11 Academy Awards. The movie tells the story of the Titanic disaster and the love story between Jack and Rose, two passengers on the ship. The movie was praised for its special effects and its attention to detail in recreating the ship and the disaster. The movie was also criticized for its historical inaccuracies and its portrayal of the events of the disaster. The movie was a box office success and became the highest-grossing film of all time at the time of its release. The movie was re-released in 3D in 2012 to coincide with the 100th anniversary of the Titanic disaster.


Summary

The Titanic was one of the largest ships of its time.

She sank during its maiden voyage.

The more luxurious the class of the passengers, the more likely they were to survive.

Crew members were even less likely to survive than 3rd-class passengers.











